openapi: 3.0.3
info:
  title: Security Plane API
  description: Security Plane API
  version: 0.0.1a
servers:
  - url: https://api.example.com/security/v0.0.1
    description: Production server
  - url: http://localhost:3000/security/v0.0.1
    description: Development server
paths:

tags:
  - name: security
    description: Operations related to security
