openapi: 3.0.3
info:
  title: Management Plane API
  description: Management Plane API
  version: 0.0.1-alpha.0.0
servers:
  - url: https://api.example.com/management/v0.0.1
    description: Production server
  - url: http://localhost:3000/management/v0.0.1
    description: Development server
paths:

tags:
  - name: management
    description: Operations related to management
