openapi: 3.0.3
info:
  title: Analysis Plane API
  description: Analysis Plane API
  version: 0.0.1a
servers:
  - url: https://api.example.com/analysis/v0.0.1
    description: Production server
  - url: http://localhost:3000/analysis/v0.0.1
    description: Development server
paths:

tags:
  - name: analysis
    description: Operations related to analysis
